language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
before_install:
  - gem uninstall -v '>= 2.0.1' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '1.16.6'

script: "bundle exec rake spec"
gemfile:
  - gemfiles/rails_4.2_pc_5_3.gemfile
  - gemfiles/rails_4.2_pc_6_0.gemfile
  - gemfiles/rails_4.2_pc_6_1.gemfile
  - gemfiles/rails_5.0_pc_5_3.gemfile
  - gemfiles/rails_5.0_pc_6_0.gemfile
  - gemfiles/rails_5.0_pc_6_1.gemfile
  - gemfiles/rails_5.1_pc_5_3.gemfile
  - gemfiles/rails_5.1_pc_6_0.gemfile
  - gemfiles/rails_5.1_pc_6_1.gemfile
